# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


movies = Movie.create([
    { title: "John Wick", tmdb_id: 245891, poster_path: "/h3VxEVUOoBZmo79O8RqKvyGiqmE.jpg", backdrop_path: "/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg", overview: "Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.", release_date: "2014-10-22",genre_ids: [28,53]},
    { title: "Raiders of the Lost Ark", tmdb_id: 85, poster_path: "/awUGN7ZCNq2EUTdpVaHDX23anOZ.jpg", backdrop_path: "/kCiMExsYuNhYluHxPP2OTmWw7hp.jpg", overview: "When Dr. Indiana Jones – the tweed-suited professor who just happens to be a celebrated archaeologist – is hired by the government to locate the legendary Ark of the Covenant, he finds himself up against the entire Nazi regime.", release_date: "1981-06-12",genre_ids: [12, 28]},
    { title: "Finding Nemo", tmdb_id: 12, poster_path: "/n5eTY87wowab53RrcU2DqdK5MNB.jpg", backdrop_path: "/6AASwDhTzI0V0JWZS8hVu6b9086.jpg", overview: "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.", release_date: "2003-05-30",genre_ids: [16, 10751]},
    { title: "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan", tmdb_id: 496, poster_path: "/h6H9jSx7nl4Jjc1zv0jUatzEyMR.jpg", backdrop_path: "/fVll3gZWsHzHl85MrdxFD7ZbCUn.jpg", overview: "Kazakh journalist Borat Sagdiyev travels to America to make a documentary. As he zigzags across the nation, Borat meets real people in real situations with hysterical consequences. His backwards behavior generates strong reactions around him exposing prejudices and hypocrisies in American culture.", release_date: "2006-11-01",genre_ids: [35]},
    { title: "The Godfather", tmdb_id: 238, poster_path: "/iVZ3JAcAjmguGPnRNfWFOtLHOuY.jpg", backdrop_path: "/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg", overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.", release_date: "1972-03-14",genre_ids: [80, 18]},
    { title: "13th", tmdb_id: 407806, poster_path: "/tcKNWD6IFPPsvkpvyZ548naz0is.jpg", backdrop_path: "/yLGeoh6HJEdA2qYmIPJ4Q2vPHdy.jpg", overview: "An in-depth look at the prison system in the United States and how it reveals the nation's history of racial inequality.", release_date: "2016-10-07",genre_ids: [99]},
    { title: "Forrest Gump", tmdb_id: 13, poster_path: "/saHP97rTPS5eLmrLQEcANmKrsFl.jpg", backdrop_path: "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg", overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.", release_date: "1994-07-06",genre_ids: [18, 35, 10749]},
    { title: "Willy Wonka & the Chocolate Factory", tmdb_id: 252, poster_path: "/vzTmO4iKZjKPLHFXu9fIUKgFBCj.jpg", backdrop_path: "/iiusvOLB4ytkZ6FSFMlGHvt33uW.jpg", overview: "Eccentric candy man Willy Wonka prompts a worldwide frenzy when he announces that golden tickets hidden inside five of his delicious candy bars will admit their lucky holders into his top-secret confectionary. But does Wonka have an agenda hidden amid a world of Oompa Loompas and chocolate rivers?", release_date: "1971-06-29",genre_ids: [10751, 35]},
    { title: "Braveheart", tmdb_id: 197, poster_path: "/or1gBugydmjToAEq7OZY0owwFk.jpg", backdrop_path: "/xRooZvuQPIc1zdIZqJM1oYT67HD.jpg", overview: "Enraged at the slaughter of Murron, his new bride and childhood love, Scottish warrior William Wallace slays a platoon of the local English lord's soldiers. This leads the village to revolt and, eventually, the entire country to rise up against English rule.", release_date: "1995-05-24",genre_ids: [36, 28, 18, 10752]},
    { title: "It", tmdb_id: 346364, poster_path: "/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg", backdrop_path: "/tcheoA2nPATCm2vvXw2hVQoaEFD.jpg", overview: "In a small town in Maine, seven children known as The Losers Club come face to face with life problems, bullies and a monster that takes the shape of a clown called Pennywise.", release_date: "2017-09-06",genre_ids: [27]},
    { title: "La La Land", tmdb_id: 313369, poster_path: "/q0dsNZOuSKzAdZod9ohPXJ4GQUs.jpg", backdrop_path: "/qJeU7KM4nT2C1WpOrwPcSDGFUWE.jpg", overview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.", release_date: "2016-11-29",genre_ids: [10402, 18, 10749]},
    { title: "The Fault in Our Stars", tmdb_id: 222935, poster_path: "/clmvI4B5JB2ToPGtiHodaLMFaoM.jpg", backdrop_path: "/jbrExTJXi07ypzwJiJNoZiGl6q3.jpg", overview: "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a patient named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel's story is about to be completely rewritten.", release_date: "2014-05-16",genre_ids: [10749, 18]},
    { title: "The Matrix", tmdb_id: 603, poster_path: "/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg", backdrop_path: "/oMsxZEvz9a708d49b6UdZK1KAo5.jpg", overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.", release_date: "1999-03-30",genre_ids: [878, 28]},
    { title: "Get Out", tmdb_id: 419430, poster_path: "/qbaIViX3tgWSTSFXbldq0ODMdi4.jpg", backdrop_path: "/vZ7EVk7FaNEWYqlVWbFLHP8Z0LU.jpg", overview: "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.", release_date: "2017-02-24",genre_ids: [53, 27,]},
    { title: "Schindler's List", tmdb_id: 424, poster_path: "/c8Ass7acuOe4za6DhSattE359gr.jpg", backdrop_path: "/w2ezhZUk7ZJH9Mdk1Y6CTmaDRg5.jpg", overview: "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.", release_date: "1993-11-30",genre_ids: [10752, 36, 18]},
    { title: "The Good, the Bad and the Ugly", tmdb_id: 429, poster_path: "/sN4h2uODctPePR8ot611XK3fdbs.jpg", backdrop_path: "/xXoc8OZ8ivVlRfuS8wQ7PTt68ss.jpg", overview: "While the Civil War rages between the Union and the Confederacy, three men – a quiet loner, a ruthless hit man and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.", release_date: "1966-12-23",genre_ids: [37]}
])